// Generated by CoffeeScript 1.11.0
(function() {
  var animal, animals, arr, i, iSpy, index, j, k, len, len1, n, plants, pluralAnimals, str, v;

  animals = ['dog', 'cat', 'bird'];

  for (index = i = 0, len = animals.length; i < len; index = ++i) {
    animal = animals[index];
    console.log(index + ':' + animal);
  }

  pluralAnimals = (function() {
    var j, len1, results;
    results = [];
    for (j = 0, len1 = animals.length; j < len1; j++) {
      animal = animals[j];
      results.push(animal + 's');
    }
    return results;
  })();

  arr = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

  for (j = 0, len1 = arr.length; j < len1; j += 2) {
    n = arr[j];
    console.log(n);
  }

  plants = {
    'p-grass': 'grass',
    'p-flower': 'flower'
  };

  for (k in plants) {
    v = plants[k];
    console.log(k + ':' + v);
  }

  str = (1 + 1) + "=" + (1 + 1);

  iSpy = 'blue';

  switch (iSpy) {
    case 'sky':
      console.log('blue');
      break;
    case 'grass':
    case 'frog':
      console.log('green');
      break;
    case 'lake':
      'dark';
      break;
    default:
      console.log('gray');
  }

}).call(this);
