// Generated by CoffeeScript 1.11.0
(function() {
  window.shop = {
    owner: {
      name: 'Programmer'
    },
    animals: [
      {
        name: 'Kelsey',
        type: 'dog',
        breed: 'Labroador',
        description: 'A sweet and loyal dog. Loves to play fetch. Sometimes drinks out of toilets'
      }, {
        name: 'Sgt. Snuffles',
        type: 'dog',
        breed: 'Pug',
        description: 'Small in status, but big in heart, Sgt.Snuffles is never one to back down from a mission'
      }, {
        name: 'Chomps',
        type: 'rabbit',
        breed: 'Giant Angora',
        description: 'Chomps is usually very good-natured, bu he does not take kindly to being mistaken for an ottoman. Come see him in person and you\'ll understand why that may happen'
      }, {
        name: 'Flops',
        type: 'rabbit',
        breed: 'Pug',
        description: 'Small in status, but big in heart, Sgt.Snuffles is never one to back down from a mission'
      }, {
        name: 'Bopper',
        type: 'rabbit',
        breed: 'Pug',
        description: 'Small in status, but big in heart, Sgt.Snuffles is never one to back down from a mission'
      }, {
        name: 'Chairman Meow',
        type: 'cat',
        breed: 'Pug',
        description: 'Small in status, but big in heart, Sgt.Snuffles is never one to back down from a mission'
      }, {
        name: 'Jacques',
        type: 'cat',
        breed: 'Pug',
        description: 'Small in status, but big in heart, Sgt.Snuffles is never one to back down from a mission'
      }, {
        name: 'Chupa',
        type: 'cat',
        breed: 'Pug',
        description: 'Small in status, but big in heart, Sgt.Snuffles is never one to back down from a mission'
      }, {
        name: 'Alfred',
        type: 'horse',
        breed: 'Pug',
        description: 'Small in status, but big in heart, Sgt.Snuffles is never one to back down from a mission'
      }
    ]
  };

}).call(this);

//# sourceMappingURL=data.js.map
