// Generated by CoffeeScript 1.11.0
(function() {
  var animal, animalSound, formatPetDescription, formatPetName, i, nameElement, petList, pets;

  nameElement = document.getElementById('owner_name');

  nameElement.innerHTML = shop.owner.name;

  document.title = shop.owner.name + '\'s Pet Shop';

  animalSound = function(animal) {
    switch (animal.type) {
      case 'cat':
        return 'meow';
      case 'dog':
        return 'bark';
      case 'horse':
      case 'dnkey':
        return 'neigh';
      default:
        return 'sniff sniff';
    }
  };

  formatPetName = function(pet) {
    return pet.name + " <span class='sound'>" + (animalSound(pet)) + "!</span>";
  };

  petList = (function() {
    var j, len, ref, results;
    ref = shop.animals;
    results = [];
    for (i = j = 0, len = ref.length; j < len; i = ++j) {
      animal = ref[i];
      results.push("<li><a href='#' onclick='selectPet(" + i + ",this)'>" + (formatPetName(animal)) + "</a></li>");
    }
    return results;
  })();

  pets = document.getElementById('available_pets');

  pets.innerHTML = petList.join('');

  formatPetDescription = function(pet) {
    return ("<h2>" + pet.name + "</h2>") + ("<h3 class='breed'>" + pet.breed + "</h3>") + ("<p class='description'>" + pet.description + "</p>");
  };

  window.selectPet = function(petIndex, element) {
    var j, len, link, pet, petInfo, ref;
    pet = shop.animals[petIndex];
    petInfo = document.getElementById("pet_information");
    petInfo.innerHTML = formatPetDescription(pet);
    ref = document.querySelectorAll("#available_pets > li > a");
    for (j = 0, len = ref.length; j < len; j++) {
      link = ref[j];
      link.className = '';
    }
    return element.className = 'selected';
  };

  window.onload = function() {
    var firstElement;
    firstElement = document.querySelector('#available_pets > li > a');
    return firstElement.click();
  };

}).call(this);

//# sourceMappingURL=setup.js.map
