// Generated by CoffeeScript 1.11.0
(function() {
  var Boat;

  Boat = (function() {
    function Boat() {}

    Boat.prototype.liftAnchor = function(doneCallback) {
      return console.log("Lifting anchor.");
    };

    Boat.prototype.setSpeed = function(speed) {
      return console.log("Adjusting speed to " + speed + " knots.");
    };

    Boat.prototype.depart = function() {
      return this.liftAnchor(function() {
        return this.setSpeed(10);
      });
    };

    return Boat;

  })();

}).call(this);
