// Generated by CoffeeScript 1.11.0
(function() {
  window.Person = (function() {
    function Person(name) {
      this.name = name;
    }

    Person.prototype.possessiveName = function() {
      var ref;
      if ((ref = this.name[this.name.length - 1]) === 's' || ref === 'x' || ref === 'z') {
        return this.name + "'";
      } else {
        return this.name + "'s";
      }
    };

    return Person;

  })();

  window.Animal = (function() {
    function Animal() {}

    Animal.fromHash = function(data) {
      var animal, key, val;
      animal = new this;
      for (key in data) {
        val = data[key];
        animal[key] = val;
      }
      return animal;
    };

    Animal.loadSeedData = function() {
      var animal, i, len, ref, results;
      ref = window.data.animals;
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        animal = ref[i];
        results.push(this.fromHash(animal));
      }
      return results;
    };

    return Animal;

  })();

}).call(this);

//# sourceMappingURL=model.js.map
