// Generated by CoffeeScript 1.11.0
(function() {
  var mainView, pet, petListView, petViews, shop;

  shop = {
    owner: new Person(data.ownerName),
    animals: Animal.loadSeedData()
  };

  petViews = (function() {
    var i, len, ref, results;
    ref = shop.animals;
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      pet = ref[i];
      results.push(new PetView(pet));
    }
    return results;
  })();

  petListView = new PetListView(petViews);

  mainView = new ShopView(shop.owner, petListView);

  mainView.render();

}).call(this);

//# sourceMappingURL=setup.js.map
