// Generated by CoffeeScript 1.11.0
(function() {
  var shop;

  shop = {
    owner: new Person(data.ownerName),
    animals: Animal.loadSeedData()
  };

}).call(this);

//# sourceMappingURL=setup.js.map
