// Generated by CoffeeScript 1.11.0
(function() {
  var slice = [].slice;

  window.PetView = (function() {
    var formattedLink;

    function PetView(pet1) {
      this.pet = pet1;
    }

    PetView.prototype.formattedDescription = function() {
      var ref;
      return ("<h2>" + pet.name + "</h2>") + ("<h3 class='breed'>" + pet.breed + " (" + ((ref = pet.age) != null ? ref : '??') + " years old)</h3>") + this.imageTag(this.pet.image) + ("<p class='description'>" + this.pet.description + "</p>");
    };

    PetView.prototype.imageTag = function(filename) {
      if (filename != null) {
        return "<img src='images/" + filename + "' />";
      } else {
        return "";
      }
    };

    PetView.prototype.formattedName = function(showBehavior) {
      var action, behavior, cssClass, ref, ref1, result, sound;
      result = this.pet.name;
      if (showBehavior) {
        ref = this.pet.behaviors(), sound = ref[0], action = ref[1];
        ref1 = sound != null ? [sound, 'sound'] : [action, 'action'], behavior = ref1[0], cssClass = ref1[1];
        result += " <span class='" + cssClass + "'>" + (behavior.toLowerCase()) + "</span>";
      }
      return result;
    };

    formattedLink = function(index, showBehavior) {
      if (showBehavior == null) {
        showBehavior = true;
      }
      return "<a href='#' onclick='selectPet(" + index + ",this)'>" + (this.formattedName(showBehavior)) + "</a>";
    };

    return PetView;

  })();

  window.PetListView = (function() {
    function PetListView(views) {
      this.views = views;
    }

    PetListView.prototype.renderList = function(filter) {
      var animal, available_pets, i, petList;
      if (filter == null) {
        filter = 'All';
      }
      petList = (function() {
        var j, len, ref, results;
        ref = this.views;
        results = [];
        for (i = j = 0, len = ref.length; j < len; i = ++j) {
          animal = ref[i];
          if (filter === 'All' || view.pet.type === filter.toLowerCase()) {
            results.push("<li>" + (view.formattedLink(i)) + "</li>");
          }
        }
        return results;
      }).call(this);
      available_pets = document.getElementById('available_pets');
      return available_pets.innerHTML = petList.join('');
    };

    PetListView.prototype.selectPet = function(petIndex, element) {
      var j, len, link, petInfo, petView, ref;
      petView = this.views[petIndex];
      petInfo = document.getElementById("pet_information");
      petInfo.innerHTML = petView.formattedDescription();
      ref = document.querySelectorAll("#available_pets > li > a");
      for (j = 0, len = ref.length; j < len; j++) {
        link = ref[j];
        link.className = '';
      }
      return element.className = 'selected';
    };

    PetListView.prototype.renderFeatured = function() {
      var chosenPetIndex, chosenPetName, chosenView, featured, featuredPets, index, j, len, listIndex, ref, ref1, view;
      featuredPets = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      chosenPetIndex = Math.floor(Math.random() * featuredPets.length);
      chosenPetName = featuredPets[chosenPetIndex];
      ref = this.views;
      for (index = j = 0, len = ref.length; j < len; index = ++j) {
        view = ref[index];
        if (view.pet.name === chosenPetName) {
          ref1 = [view, index], chosenView = ref1[0], listIndex = ref1[1];
        }
      }
      featured = document.getElementById('featured');
      if (listIndex != null) {
        return featured.innerHTML = "<span class='title'>Featured Pet</span>" + chosenView.formattedLink(listIndex, false);
      } else {
        return featured.innerHTML = "<span class='title'>Featured Pet</span><a href='#'>No Pet</a>";
      }
    };

    PetListView.prototype.renderFilteringBar = function() {
      var filterOpt, filterOutput, type;
      filterOutput = (function() {
        var j, len, ref, results;
        ref = ['All', 'Dog', 'Cat', 'Rabbit', 'Horse'];
        results = [];
        for (j = 0, len = ref.length; j < len; j++) {
          type = ref[j];
          results.push("<li><a href='#' onclick='displayPetList(\"" + type + "\")'>" + type + "</a></li>");
        }
        return results;
      })();
      filterOpt = document.getElementById('filtering_opts');
      return filterOpt.innerHTML = filterOutput.join('');
    };

    PetListView.prototype.render = function() {
      this.renderList();
      this.renderFilteringBar();
      this.renderFeatured('Chupa', 'Kelsey', 'Flopa');
      window.listView = this;
      window.displayPetList = function(filterType) {
        return window.listView.renderList(filterType);
      };
      return window.selectPet = function(index, element) {
        return window.listView.selectPet(index, element);
      };
    };

    return PetListView;

  })();

  window.ShopView = (function() {
    function ShopView(owner, mainContent) {
      this.owner = owner;
      this.mainContent = mainContent;
    }

    ShopView.prototype.render = function() {
      var nameElement;
      return nameElement = document.getElementById('owner_name');
    };

    return ShopView;

  })();

}).call(this);

//# sourceMappingURL=view.js.map
