// Generated by CoffeeScript 1.11.0
(function() {
  var test, yeti;

  yeti = 1;

  if (yeti != null) {
    console.log("I want to believe");
  }

  test = null;

  if (test == null) {
    test = 'a';
  }

  test || (test = 'm');

}).call(this);
