// Generated by CoffeeScript 1.11.0
(function() {
  var data, key, t, val;

  data = ['k1', 'k2', 'k3', 'k4'];

  t = [];

  for (key in data) {
    val = data[key];
    t[key] = val;
  }

  console.log(t[0]);

  console.log(key);

}).call(this);
