// Generated by CoffeeScript 1.11.0
(function() {
  var animal, nameElement, petList, pets, shop;

  shop = {
    owner: {
      name: 'Programmer'
    },
    animals: [
      {
        name: 'Kelsey',
        type: 'dog'
      }, {
        name: 'Sgt. Snuffles',
        type: 'dog'
      }, {
        name: 'Chomps',
        type: 'rabbit'
      }, {
        name: 'Flops',
        type: 'rabbit'
      }, {
        name: 'Bopper',
        type: 'rabbit'
      }, {
        name: 'Chairman Meow',
        type: 'cat'
      }, {
        name: 'Jacques',
        type: 'cat'
      }, {
        name: 'Chupa',
        type: 'cat'
      }, {
        name: 'Alfred',
        type: 'horse'
      }
    ]
  };

  nameElement = document.getElementById('owner_name');

  nameElement.innerHTML = shop.owner.name;

  document.title = shop.owner.name + '\'s Pet Shop';

  petList = (function() {
    var i, len, ref, results;
    ref = shop.animals;
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      animal = ref[i];
      results.push('<li>' + animal.name + '</li>');
    }
    return results;
  })();

  pets = document.getElementById('available_pets');

  pets.innerHTML = petList.join('');

}).call(this);

//# sourceMappingURL=setup.js.map
