// Generated by CoffeeScript 1.11.0
(function() {
  var nameElement, shop;

  shop = {
    owner: {
      name: 'Usst'
    }
  };

  nameElement = document.getElementById('owner_name');

  nameElement.innerHTML = shop.owner.name;

  document.title = shop.owner.name + "'s a Pet shop";

}).call(this);
